"""Research Agent (PRD §6).

Pipeline — deterministic data first, language model second:
1. Resolve the query to tickers (regex / aliases / symbol search / LLM extraction).
2. Gather facts with tools in parallel (quote, profile, financials, valuation,
   SEC filings, news, web). Every fact gets a source id (S1, S2, ...).
3. Numeric tables (Financial Snapshot, Valuation) are rendered by the app from
   the data — never generated by the model.
4. The LLM writes the narrative sections from the facts pack only, citing [S#]
   and labelling Fact / Interpretation / Unknown.
5. Sources are appended deterministically.
"""
from __future__ import annotations

import asyncio
import json
import logging
import re
from collections.abc import AsyncIterator
from datetime import datetime, timezone
from typing import Any

from app.agents.common import detect_tickers
from app.prompts import policies as P
from app.providers import registry
from app.providers.llm.base import LLMNotConfigured, LLMUnavailable
from app.providers.types import ProviderError
from app.services import market_data

log = logging.getLogger(__name__)
TICKER_RE = re.compile(r"^\$?[A-Za-z]{1,5}(?:[-.][A-Za-z])?$")

SECTIONS = {
    "deep": [
        ("company", "Company in One Minute", "一分钟了解公司"),
        ("business_model", "Business Model", "商业模式"),
        ("customers", "Why Customers Choose It", "为什么客户会选择它"),
        ("growth", "Growth Drivers", "增长来源"),
        ("financials", "Financial Snapshot", "财务快照"),
        ("valuation", "Valuation", "估值"),
        ("bull", "Bull Case", "乐观情景"),
        ("bear", "Bear Case", "悲观情景"),
        ("thesis_change", "What Could Change the Thesis", "什么会改变判断"),
        ("next_questions", "Questions to Ask Next", "下一步应该研究什么"),
    ],
    "quick": [
        ("company", "Company in One Minute", "一分钟了解公司"),
        ("financials", "Financial Snapshot", "财务快照"),
        ("bull", "Bull Case", "乐观情景"),
        ("bear", "Bear Case", "悲观情景"),
        ("facts", "5 Important Facts", "5 个重要事实"),
    ],
    "topic": [
        ("key_idea", "Key Idea", "核心概念"),
        ("how_it_works", "How It Works", "它是怎么运作的"),
        ("example", "A Simple Example", "一个简单的例子"),
        ("risks", "Risks and Common Misconceptions", "风险与常见误解"),
        ("next_questions", "Questions to Ask Next", "下一步应该研究什么"),
    ],
}


def heading(i: int, en: str, zh: str, language: str) -> str:
    return f"## {i}. {zh}（{en}）" if language.startswith("zh") else f"## {i}. {en}"


# --------------------------------------------------------------------------- resolution

async def resolve_symbols(query: str, language: str) -> list[str]:
    q = query.strip()
    if TICKER_RE.match(q):
        sym = q.replace("$", "").upper().replace(".", "-")
        try:
            await asyncio.to_thread(market_data.get_quote, sym)
            return [sym]
        except ProviderError:
            pass
    found = []
    for t in detect_tickers(q):
        try:
            await asyncio.to_thread(market_data.get_quote, t)
            found.append(t)
        except ProviderError:
            continue
    if found:
        return found
    # Company name search on the raw query (works for "Apple", "Nvidia" ...).
    if len(q) <= 40 and not re.search(r"[一-鿿]", q):
        try:
            rows = await asyncio.to_thread(market_data.search_symbols, q, 3)
            if rows:
                return [rows[0].symbol]
        except ProviderError:
            pass
    # Ask the LLM only to *extract company names*; resolution still goes through search.
    try:
        llm = registry.llm_provider()
        resp = await llm.chat([
            {"role": "system", "content": "Extract the public companies or ETFs mentioned in the user's question. Reply ONLY with JSON "
                                          '{"companies": ["English company name", ...], "tickers": ["US ticker if certain", ...]}. '
                                          "Use empty lists if none. Max 3."},
            {"role": "user", "content": q},
        ], json_mode=True, temperature=0, max_tokens=200)
        text = resp.content
        data = json.loads(text[text.find("{"): text.rfind("}") + 1] or "{}")
    except (LLMUnavailable, ValueError):
        data = {}
    out: list[str] = []
    for t in (data.get("tickers") or [])[:3]:
        t = str(t).upper().strip()
        try:
            await asyncio.to_thread(market_data.get_quote, t)
            if t not in out:
                out.append(t)
        except ProviderError:
            continue
    for name in (data.get("companies") or [])[:3]:
        if len(out) >= 3:
            break
        try:
            rows = await asyncio.to_thread(market_data.search_symbols, str(name), 2)
            if rows and rows[0].symbol not in out:
                out.append(rows[0].symbol)
        except ProviderError:
            continue
    return out[:3]


# --------------------------------------------------------------------------- data gathering

class SourceBook:
    def __init__(self):
        self.items: list[dict] = []

    def add(self, title: str, url: str | None, publisher: str | None, kind: str, published_at: str | None = None,
            snippet: str | None = None) -> str:
        for it in self.items:
            if url and it["url"] == url:
                return it["ref"]
        ref = f"S{len(self.items) + 1}"
        self.items.append({"ref": ref, "title": title, "url": url, "publisher": publisher, "kind": kind,
                           "published_at": published_at, "snippet": (snippet or "")[:500],
                           "retrieved_at": datetime.now(timezone.utc).isoformat()})
        return ref


def _b(v: float | None) -> str | None:
    if v is None:
        return None
    a = abs(v)
    if a >= 1e12:
        return f"{v / 1e12:.2f}T"
    if a >= 1e9:
        return f"{v / 1e9:.2f}B"
    if a >= 1e6:
        return f"{v / 1e6:.1f}M"
    return f"{v:,.0f}"


def _pct(v: float | None) -> str | None:
    return None if v is None else f"{v * 100:.1f}%"


async def _safe(fn, *args):
    try:
        return await asyncio.to_thread(fn, *args), None
    except ProviderError as e:
        return None, str(e)
    except Exception as e:  # pragma: no cover
        log.warning("research fetch failed %s: %s", getattr(fn, "__name__", fn), e)
        return None, "unavailable"


async def gather_company(symbol: str, mode: str, book: SourceBook) -> tuple[dict, dict]:
    """Return (facts_for_llm, structured_for_ui) for one symbol."""
    deep = mode == "deep"
    (quote, _), (profile, _), (metrics, _), (fin, _), (cnews, _), (filings, _) = await asyncio.gather(
        _safe(market_data.get_quote, symbol), _safe(market_data.get_company_profile, symbol), _safe(market_data.get_metrics, symbol),
        _safe(market_data.get_financials, symbol, 5 if deep else 4), _safe(market_data.get_company_news, symbol, 8 if deep else 5),
        _safe(market_data.get_filings, symbol, 3 if deep else 1),
    )
    name = (profile.name if profile else None) or (quote.name if quote else None) or symbol
    web_results: list = []
    news_results: list = []
    if deep:
        qs = [f"{name} business model how does it make money", f"{name} competitive advantage competitors",
              f"{name} biggest risks challenges"]
        res = await asyncio.gather(*[_safe(market_data.search_web, q, 4) for q in qs], _safe(market_data.search_news, f"{name} stock", 5))
        for r, _ in res[:-1]:
            web_results += r or []
        news_results = res[-1][0] or []

    facts: dict[str, Any] = {"ticker": symbol, "name": name}
    ui: dict[str, Any] = {"ticker": symbol, "name": name, "data_status": {}}
    if quote:
        ref = book.add(f"{symbol} market quote", f"https://finance.yahoo.com/quote/{symbol}", quote.source, "market", quote.timestamp.isoformat())
        facts["quote"] = {"price_usd": float(quote.price), "change_pct_today": float(quote.change_pct) if quote.change_pct is not None else None,
                          "session": quote.session, "as_of": quote.timestamp.isoformat(), "source": ref}
        ui["quote"] = {**quote.model_dump(mode="json"), "ref": ref}
    ui["data_status"]["quote"] = bool(quote)
    if profile:
        ref = book.add(f"{name} company profile", profile.source_url, profile.source, "fundamentals")
        facts["profile"] = {"sector": profile.sector, "industry": profile.industry, "country": profile.country, "employees": profile.employees,
                            "type": profile.quote_type, "summary": (profile.summary or "")[:2000], "source": ref}
        ui["profile"] = {**profile.model_dump(mode="json"), "ref": ref}
    ui["data_status"]["profile"] = bool(profile)
    if fin and fin.periods:
        ref = book.add(f"{symbol} annual financial statements", fin.source_url, fin.source, "fundamentals")
        facts["annual_financials"] = {"source": ref, "currency": fin.currency, "periods": [{
            "fiscal_year": p.fiscal_year, "period_end": p.period_end, "revenue": _b(p.revenue), "revenue_growth": _pct(p.revenue_growth),
            "net_income": _b(p.net_income), "eps_diluted": p.eps_diluted, "free_cash_flow": _b(p.free_cash_flow),
            "gross_margin": _pct(p.gross_margin), "operating_margin": _pct(p.operating_margin), "cash": _b(p.cash),
            "total_debt": _b(p.total_debt)} for p in fin.periods]}
        ui["financials"] = {**fin.model_dump(mode="json"), "ref": ref}
    ui["data_status"]["financials"] = bool(fin and fin.periods)
    if metrics:
        ref = book.add(f"{symbol} valuation statistics", metrics.source_url, metrics.source, "fundamentals")
        facts["valuation"] = {"market_cap": _b(metrics.market_cap), "pe_ttm": _r(metrics.pe_ttm), "pe_forward": _r(metrics.pe_forward),
                              "price_to_sales": _r(metrics.ps_ttm), "fcf_yield": _pct(metrics.fcf_yield), "dividend_yield": _pct(metrics.dividend_yield),
                              "week52_high": metrics.week52_high, "week52_low": metrics.week52_low, "beta": _r(metrics.beta), "source": ref}
        ui["valuation"] = {**metrics.model_dump(mode="json"), "ref": ref}
    ui["data_status"]["valuation"] = bool(metrics)
    facts["filings"] = [{"title": f.title, "date": f.published_at, "source": book.add(f.title, f.url, f.publisher, "filing", f.published_at, f.snippet)}
                        for f in (filings or [])]
    news = (cnews or []) + news_results
    facts["news"] = [{"headline": n.title, "publisher": n.publisher, "date": n.published_at, "summary": (n.snippet or "")[:300],
                      "source": book.add(n.title, n.url, n.publisher, "news", n.published_at, n.snippet)} for n in news[:10]]
    facts["web"] = [{"title": w.title, "snippet": (w.snippet or "")[:400],
                     "source": book.add(w.title, w.url, w.publisher, "web", w.published_at, w.snippet)} for w in web_results[:9]]
    ui["data_status"]["news"] = bool(news)
    return facts, ui


def _r(v: float | None) -> float | None:
    return None if v is None else round(v, 2)


# --------------------------------------------------------------------------- writing

def report_system_prompt(mode: str, language: str, age_group: str, comparison: bool) -> str:
    secs = SECTIONS[mode]
    heads = "\n".join(heading(i + 1, en, zh, language) for i, (_, en, zh) in enumerate(secs))
    zh = language.startswith("zh")
    labels = "**事实**、**解读**、**未知**" if zh else "**Fact**, **Interpretation**, **Unknown**"
    unavailable = "数据暂缺" if zh else "Data unavailable"
    return "\n\n".join([
        "You are the Research Agent of a children's investment-education app. You write a clear, honest, source-backed research "
        "report that teaches HOW to research a company. It is not a recommendation.",
        P.age_block(age_group, language),
        P.language_block(language),
        f"""STRICT DATA RULES:
- Use ONLY the facts in the FACTS PACK provided by the user message. Every number you write must appear in the facts pack.
- Cite facts with their source id in square brackets, e.g. [S3]. Do not cite ids that do not exist.
- If something is not in the facts pack, write "{unavailable}" — never guess or use memory for current figures.
- The app already shows the numeric Financial Snapshot and Valuation tables above your text. In those sections, explain what the
  trends mean in words and cite; do not re-list every number.
- Start bullet points in analytical sections with one of the labels {labels} so the student can tell facts from opinions.
- Valuation must include this idea: a high valuation is not automatically expensive and a low one is not automatically cheap;
  valuation must be judged together with growth, quality and risk.
- Never give a Buy/Hold/Sell rating, price target or short-term price prediction.""",
        f"""FORMAT: Markdown. Use exactly these section headings, in this order, and nothing before the first heading:
{heads}
{"Bull Case and Bear Case: 3-5 bullets each. Growth Drivers: 3-5 bullets." if mode == "deep" else ""}
{"5 Important Facts: exactly five bullets, each a fact with a citation." if mode == "quick" else ""}
{"This is a COMPARISON of several companies: compare them side by side inside each section." if comparison else ""}
Do not add a Sources section (the app adds it).""",
    ])


def _facts_message(query: str, facts: Any) -> str:
    return (f"STUDENT QUESTION: {query}\n\nFACTS PACK (retrieved just now; cite with [S#]):\n"
            + json.dumps(facts, ensure_ascii=False, default=str, indent=1)[:28000])


def sources_markdown(sources: list[dict], language: str, idx: int) -> str:
    zh = language.startswith("zh")
    lines = [f"## {idx}. {'来源（Sources）' if zh else 'Sources'}"]
    for s in sources:
        date = f" — {s['published_at'][:10]}" if s.get("published_at") else ""
        pub = f" · {s['publisher']}" if s.get("publisher") else ""
        link = f"[{s['title']}]({s['url']})" if s.get("url") else s["title"]
        lines.append(f"- **[{s['ref']}]** {link}{pub}{date}")
    retrieved = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append("")
    lines.append(f"_{'数据获取时间' if zh else 'Data retrieved'}: {retrieved}_")
    return "\n".join(lines)


def clean_citations(text: str, valid: set[str]) -> str:
    return re.sub(r"\[(S\d+)\]", lambda m: m.group(0) if m.group(1) in valid else "", text)


DISCLAIMER = {
    "en-US": "_This report is for learning only. It is not investment advice and does not tell you to buy or sell anything._",
    "zh-CN": "_本报告仅用于学习，不构成投资建议，也不建议你买入或卖出任何股票。_",
}


async def run_research(query: str, mode: str, language: str, age_group: str) -> AsyncIterator[dict]:
    """Yields: status | resolved | data | token | final | error."""
    llm = registry.llm_provider()
    yield {"type": "status", "step": "resolving"}
    symbols = await resolve_symbols(query, language)
    yield {"type": "resolved", "symbols": symbols}
    book = SourceBook()
    effective_mode = mode if symbols else "topic"
    yield {"type": "status", "step": "gathering"}
    if symbols:
        results = await asyncio.gather(*[gather_company(s, mode if len(symbols) == 1 else "quick", book) for s in symbols])
        facts = [f for f, _ in results] if len(symbols) > 1 else results[0][0]
        ui = {"symbols": symbols, "companies": [u for _, u in results]}
        if not any(u["data_status"].get("quote") or u["data_status"].get("profile") for _, u in results):
            yield {"type": "error", "code": "DATA_UNAVAILABLE"}
            return
    else:
        (web, _), (news, _) = await asyncio.gather(_safe(market_data.search_web, query, 6), _safe(market_data.search_news, query, 4))
        facts = {"web": [{"title": w.title, "snippet": (w.snippet or "")[:500], "source": book.add(w.title, w.url, w.publisher, "web", w.published_at, w.snippet)} for w in (web or [])],
                 "news": [{"headline": n.title, "summary": (n.snippet or "")[:300], "source": book.add(n.title, n.url, n.publisher, "news", n.published_at, n.snippet)} for n in (news or [])]}
        ui = {"symbols": [], "companies": []}
    ui.update({"mode": effective_mode, "sections": [s[0] for s in SECTIONS[effective_mode]], "query": query,
               "prompt_version": P.PROMPT_VERSION})
    yield {"type": "data", "structured": ui, "sources": book.items}
    yield {"type": "status", "step": "writing"}

    messages = [{"role": "system", "content": report_system_prompt(effective_mode, language, age_group, len(symbols) > 1)},
                {"role": "user", "content": _facts_message(query, facts)}]
    text = ""
    try:
        async for ev in llm.stream_chat(messages, temperature=0.3, max_tokens=4096 if effective_mode == "deep" else 2000):
            if ev.kind == "content":
                text += ev.text
                yield {"type": "token", "text": ev.text}
            elif ev.kind == "notice":
                yield {"type": "notice", "code": ev.text}
    except LLMUnavailable as e:
        log.warning("LLM unavailable during research: %s", e)
        code = "AI_NOT_CONFIGURED" if isinstance(e, LLMNotConfigured) else "AI_UNAVAILABLE"
        yield {"type": "error", "code": code, "structured": ui, "sources": book.items}
        return
    valid = {s["ref"] for s in book.items}
    body = clean_citations(text.strip(), valid)
    used = set(re.findall(r"\[(S\d+)\]", body))
    # keep all data-provider sources + any cited source, drop uncited web noise
    kept = [s for s in book.items if s["ref"] in used or s["kind"] in ("market", "fundamentals", "filing")]
    md = body + "\n\n" + sources_markdown(kept, language, len(SECTIONS[effective_mode]) + 1) + "\n\n" + DISCLAIMER.get(language, DISCLAIMER["en-US"])
    yield {"type": "final", "content_markdown": md, "structured": ui, "sources": kept, "model": getattr(llm, "model", "")}
