"""initial schema

Revision ID: 8696d11d7b96
Revises: 
Create Date: 2026-09-24 06:52:56.043310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8696d11d7b96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('families',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data_cache',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('master_personas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('name_zh', sa.String(length=80), nullable=False),
    sa.Column('avatar', sa.String(length=64), nullable=False),
    sa.Column('short_bio_en', sa.Text(), nullable=False),
    sa.Column('short_bio_zh', sa.Text(), nullable=False),
    sa.Column('philosophy_tags', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('knowledge_base_ids', sa.JSON(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('age_group', sa.String(length=1), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('avatar', sa.String(length=32), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('allow_etf', sa.Boolean(), nullable=False),
    sa.Column('allow_fractional', sa.Boolean(), nullable=False),
    sa.Column('daily_ai_limit', sa.Integer(), nullable=True),
    sa.Column('daily_minutes_limit', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('pin_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'day', name='uq_ai_usage_day')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_profile_id'), ['profile_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('master_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_profile_id'), ['profile_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('trade_id', sa.String(length=32), nullable=True),
    sa.Column('research_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_symbol'), ['symbol'], unique=False)

    op.create_table('learning_progress',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'card_id', name='uq_learning')
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_profile_id'), ['profile_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference_id', sa.String(length=96), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'epoch', 'reference_id', 'type', name='uq_ledger_ref')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_epoch'), ['epoch'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_profile_id'), ['profile_id'], unique=False)

    op.create_table('research_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('age_group', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('structured_json', sa.JSON(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_reports_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_reports_symbol'), ['symbol'], unique=False)

    op.create_table('simulation_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_corporate_action_check', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('trades',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_price', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('fee', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('source_price_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_source', sa.String(length=64), nullable=True),
    sa.Column('session', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reject_reason', sa.String(length=64), nullable=True),
    sa.Column('journal_note', sa.Text(), nullable=True),
    sa.Column('research_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'symbol', name='uq_watch')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_profile_id'), ['profile_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('research_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.String(length=40), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sources_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sources_report_id'))

    op.drop_table('research_sources')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_profile_id'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_profile_id'))

    op.drop_table('trades')
    op.drop_table('simulation_accounts')
    with op.batch_alter_table('research_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_reports_symbol'))
        batch_op.drop_index(batch_op.f('ix_research_reports_profile_id'))

    op.drop_table('research_reports')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_profile_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_epoch'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_profile_id'))

    op.drop_table('learning_progress')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_symbol'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_profile_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_profile_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_profile_id'))

    op.drop_table('ai_usage')
    op.drop_table('users')
    op.drop_table('child_profiles')
    op.drop_table('master_personas')
    op.drop_table('market_data_cache')
    op.drop_table('families')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
